### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gootik**

### CODE REVIEW

**Comment by bigodines** [comment]
:lgtm:

**Comment by amokhtar** [comment]
LGTM

**Comment by raydog** [comment]
😢

**Comment by gootik** [comment]
@raydog you can take over if you want!

**Comment by raydog** [comment]
@shezarkhani I forked it + fixed outstanding bugs right after making that comment. :)

[raydog/redsentinel](https://github.com/raydog/redsentinel)

**Comment by gootik** [comment]
@raydog niiice. Do you want to take over this repo too? Or should we add a note to point ppl towards your fork.

**Comment by raydog** [comment]
@shezarkhani A simple note would be fine. :)

**Pull request merged**
